export const siteConfig = {
  name: "Tukku's Kitchen",
  shortName: "Tukku's",
  url: 'https://tukkuskitchen.com',
  orderUrl: 'https://tukkuskitchen.petpooja.site/',
  telephone: '+918962249989',
  whatsapp: 'https://wa.me/918962249989',
  email: 'tukkuskitchen@gmail.com',
  address: {
    streetAddress: 'Near Katni-Rewa Highway, Katni Road Maihar',
    addressLocality: 'Maihar',
    addressRegion: 'Madhya Pradesh',
    postalCode: '484446',
    addressCountry: 'India',
  },
  priceRange: '$$',
  cuisine: ['Vegetarian', 'Jain', 'North Indian', 'South Indian', 'Chinese', 'Snacks', 'Breakfast', 'Lunch', 'Dinner'],
  services: ['Dine-In', 'Takeaway', 'Online Ordering', 'WhatsApp Ordering', 'Phone Ordering', 'Family Dining'],
  audience: ['Families', 'Travelers', 'Highway Visitors', 'Pilgrims visiting Maihar', 'Vegetarian Food Lovers', 'Jain Customers'],
  keywords: [
    "Tukku's Kitchen",
    'Best Vegetarian Restaurant Maihar',
    'Jain Restaurant Maihar',
    'Veg Restaurant Maihar',
    'Restaurant Near Katni Rewa Highway',
    'Family Restaurant Maihar',
    'Pure Veg Restaurant',
    'Jain Food',
    'Vegetarian Food',
    'Indian Restaurant',
    'Healthy Food',
    'Restaurant MP',
    'Takeaway',
    'Online Food Order',
    'Restaurant Near Me',
  ],
  openGraphTitle: "Tukku's Kitchen | Vegetarian & Jain Restaurant",
  openGraphDescription: 'Fresh Vegetarian & Jain Cuisine in Maihar. Order Online. Family Dining. Near Katni-Rewa Highway.',
  image: '/pic1.jpeg',
  themeColor: '#2E7D32',
  backgroundColor: '#FFFDF8',
  manifest: '/manifest.json',
  favicon: '/favicon.svg',
  appleTouchIcon: '/favicon.svg',
  msTileColor: '#2E7D32',
  social: {
    facebook: 'https://facebook.com',
    instagram: 'https://instagram.com',
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
  defaultSeo: {
    title: "Tukku's Kitchen | Best Vegetarian & Jain Restaurant in Maihar",
    description:
      'Experience fresh vegetarian and Jain cuisine at Tukku’s Kitchen in Maihar, Madhya Pradesh. Located near Katni-Rewa Highway, enjoy delicious meals, family dining, takeaway, WhatsApp ordering, and online ordering.',
    keywords: [
      "Tukku's Kitchen",
      'Best Vegetarian Restaurant Maihar',
      'Jain Restaurant Maihar',
      'Veg Restaurant Maihar',
      'Restaurant Near Katni Rewa Highway',
      'Family Restaurant Maihar',
      'Pure Veg Restaurant',
      'Jain Food',
      'Vegetarian Food',
      'Indian Restaurant',
      'Healthy Food',
      'Restaurant MP',
      'Takeaway',
      'Online Food Order',
      'Restaurant Near Me',
    ],
    canonical: '/',
    url: '/',
    type: 'website',
    image: '/pic1.jpeg',
  },
};

export const restaurantSchema = {
  '@context': 'https://schema.org',
  '@type': 'Restaurant',
  name: siteConfig.name,
  description: siteConfig.defaultSeo.description,
  image: [siteConfig.image],
  telephone: siteConfig.telephone,
  email: siteConfig.email,
  url: siteConfig.url,
  priceRange: siteConfig.priceRange,
  servesCuisine: siteConfig.cuisine,
  address: {
    '@type': 'PostalAddress',
    streetAddress: siteConfig.address.streetAddress,
    addressLocality: siteConfig.address.addressLocality,
    addressRegion: siteConfig.address.addressRegion,
    postalCode: siteConfig.address.postalCode,
    addressCountry: siteConfig.address.addressCountry,
  },
  geo: {
    '@type': 'GeoCoordinates',
    latitude: '',
    longitude: '',
  },
  openingHoursSpecification: [
    {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      opens: '11:00',
      closes: '22:30',
    },
  ],
  sameAs: [siteConfig.social.facebook, siteConfig.social.instagram, siteConfig.social.twitter, siteConfig.social.linkedin],
  potentialAction: [
    {
      '@type': 'OrderAction',
      target: siteConfig.orderUrl,
      actionPlatform: ['http://schema.org/Online', 'http://schema.org/WhatsApp'],
    },
  ],
};
